travis:
  secure:
    BINSTAR_TOKEN: mqrpV9kj1irFhSfHJT7XS3JenGj5aFvNRIYyU8baNG1GWlm7pIcoFX3yWtNKbDs230pBOkXyG7NazaU1uXsXYuh+HMqiSSQjPKqJF+FRDN+4nHjuNK8/YqbiBBouT7mMo60NSMfOOyouH02X0GxKKhSpFsdBsjyHTL5SkSBtChBhIeRRqUhOJpRb4yv/eR4ILk12J6OB5+uC2huEsYOSN8Z04plrgPE7o1S8hmsDt4b7GpMd9g1NnjM/1vOO2i0C3g3/3bZFsSEA7B0wcxMg9e8qsam+WNW/GOaqdqNpn+vnzKPblTiewiu5JkHU41iUBuq1WHsm+BhnZoPEYtHXxOWNHOhpdea70E6OSWwqXGQtykb5U3yUY9DQWvTtKA8bEauVdcWTiEyUcYbjbaf0TG/PCzjECIWrxW3ScGpRPjY4iBPC73x/6OdR/5E7uBr3ptjFvWCsJZZC1ddr+4Ozu5KAenqLFU7t7YLky+13zK/7ZIVKVZoajkmlsTJf/7fFoFuLsAyDZSPAq2uKlq6PWvCPS776UULU4ODFkR11HzqFn8Bz05jR1JvLxpBwYi5q8ucFD5rl9ATh+WgSfcFiF8XBxJJk6pHnOY5ADUMuHLhnlFEvvIxpEZUxoPd1yjbAFfie9MUdta8ENatdWSKbNCkZKJYhLiW2MS7VeRS3bEg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
